### ISSUE TITLE
Merge this repo in the main dotty repo?

### ISSUE THREAD

**Issue by smarter** [lampepfl/sbt-dotty#7]
@felixmulder What do you think? Any particular reason to keep this in a separate repo?

**Comment by felixmulder** [comment]
As long as it can evolve separately from the compiler, I don't really have an opinion on where we put it.

One argument against is that there's a lot of noise in the Dotty repo - we might as well merge the drone repo with the dotty repo otherwise.

**Comment by smarter** [comment]
I don't understand, what noise? I'd like to get everything in the same repo so that all the tests are run in one place, and so that when I make a breaking change, I can make the same breaking change to the sbt plugin. Scala.js does the same: https://github.com/scala-js/scala-js/tree/master/sbt-plugin/src/main

**Comment by felixmulder** [comment]
Perfectly fine by me (=

**Comment by OlivierBlanvillain** [comment]
LGTM as well!

**Comment by smarter** [comment]
This is now done but someone needs to push a commit to mark this project as obsolete and point to the new location, @felixmulder could you do that please?
