### ISSUE TITLE
scalaBinaryVersion breaks coursier

### ISSUE THREAD

**Issue by MasseGuillaume** [lampepfl/sbt-dotty#9]
given `api211JVM` a scala 2.11 project

I cannot use

`lazy val runtimeDotty = project.dependsOn(api211JVM)`

it will try to fetch `api_0.1`

**Comment by smarter** [comment]
This project is obsolete, sbt-dotty is now part of dotty itself: https://github.com/lampepfl/dotty/tree/master/sbt-dotty, please reopen an issue against dotty.

Also, could you give more detaisl? Is this problem specific to coursier?

**Comment by MasseGuillaume** [comment]
https://github.com/lampepfl/dotty/issues/2409
